// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Curry   = require("bs-platform/lib/js/curry.js");
var React   = require("react");
var ReactRe = require("reason-react/lib/js/src/reactRe.js");

var include = ReactRe.Component[/* Stateful */8];

var componentWillUpdate = include[1];

var componentDidUpdate = include[2];

var componentWillReceiveProps = include[3];

var componentWillUnmount = include[4];

var getInstanceVars = include[5];

var jsPropsToReasonProps = include[6];

function getInitialState() {
  return /* float array */[
          0.0,
          0.0
        ];
}

var name = "Geolocation";

function componentDidMount(param) {
  var stateSetter = function () {
    return /* float array */[
            1.1,
            1.1
          ];
  };
  Curry._1(param[/* setState */5], stateSetter);
  return /* None */0;
}

function render(param) {
  return React.createElement("div", undefined, param[/* props */1][/* message */0]);
}

var Geolocation_006 = /* JsProps */include[7];

var Geolocation_007 = /* InstanceVars */include[8];

var Geolocation = /* module */[
  /* componentWillUpdate */componentWillUpdate,
  /* componentDidUpdate */componentDidUpdate,
  /* componentWillReceiveProps */componentWillReceiveProps,
  /* componentWillUnmount */componentWillUnmount,
  /* getInstanceVars */getInstanceVars,
  /* jsPropsToReasonProps */jsPropsToReasonProps,
  Geolocation_006,
  Geolocation_007,
  /* getInitialState */getInitialState,
  /* name */name,
  /* componentDidMount */componentDidMount,
  /* render */render
];

var include$1 = ReactRe.CreateComponent([
      name,
      getInstanceVars,
      getInitialState,
      componentDidMount,
      componentWillReceiveProps,
      componentWillUpdate,
      componentDidUpdate,
      componentWillUnmount,
      jsPropsToReasonProps,
      render
    ]);

var wrapProps = include$1[1];

function createElement(message) {
  return Curry._1(wrapProps, /* record */[/* message */message]);
}

var comp = include$1[0];

exports.Geolocation   = Geolocation;
exports.comp          = comp;
exports.wrapProps     = wrapProps;
exports.createElement = createElement;
/* include Not a pure module */
