// Generated by BUCKLESCRIPT VERSION 1.7.1, PLEASE EDIT WITH CARE
'use strict';

var Curry       = require("bs-platform/lib/js/curry.js");
var ReactDOMRe  = require("reason-react/lib/js/src/reactDOMRe.js");
var Geolocation = require("./geolocation.js");

ReactDOMRe.renderToElementWithId(Curry._4(Geolocation.createElement("Your location is "), /* [] */0, /* None */0, /* None */0, /* () */0), "index");

/*  Not a pure module */
